name: e2e_test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Zot (OCI Registry)
        run: |
          sudo wget -O /usr/bin/zot https://github.com/project-zot/zot/releases/download/v2.1.0/zot-linux-amd64
          sudo chmod +x /usr/bin/zot
          sudo chown root:root /usr/bin/zot
      - name: Run tests with pytest
        run: pytest tests
